#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config \
	/data

# remove config-lock
[[ -f /config/.config-lock ]] && \
  { echo "Removing lockfile"; rm -f /config/.config-lock; }

# copy config.yml
[[ -f /config/config.yml ]] && \
  { echo "Using existing config.yml"; } || \
	{ echo "New config.yml from template"; cp /defaults/config.example.yml /config/config.yml; }

# install custom plugins
if [[ ! -z "${FG_PLUGINS}" ]]; then
  mkdir -p /config/plugins
  for plugin_name in ${FG_PLUGINS}; do
    plugin_src="/defaults/plugins/${plugin_name}.py"
    plugin_trg="/config/plugins/${plugin_name}.py"
    plugin_log="Installing plugin: '${plugin_name}'"
    if [[ -f "${plugin_src}" ]]; then
      if  [[ ! -f "${plugin_trg}" ]]; then
        cp "${plugin_src}" "${plugin_trg}" >/dev/null 2>&1 && \
          echo "${plugin_log} - successful" || \
          echo "${plugin_log} - copy failed"
      else
        echo "${plugin_log} - already exists. skipping ..."
      fi
    else
      echo "${plugin_log} - no such plugin available"
    fi
  done
fi

# set FG_WEBUI_PASSWD
if [[ ! -z "${FG_WEBUI_PASSWD}" ]]; then
  echo "Setting flexget web password to '${FG_WEBUI_PASSWD}'"
  RESULT=$(flexget -c /config/config.yml web passwd "${FG_WEBUI_PASSWD}" 2>&1)
  echo ${RESULT} | grep -q 'Updated password' && echo "${RESULT}" || \
    { echo "${RESULT}"; exit 1; }
fi

# permissions
if [ "${FIX_DIR_OWNERSHIP_CONFIG}" = "1" ] || [ "${FIX_DIR_OWNERSHIP_CONFIG}" = "true" ]; then
  find /config \! \( -uid $(id -u abc) -gid $(id -g abc) \) -print0 | \
    xargs -0 --no-run-if-empty chown -h abc:abc
fi
if [ "${FIX_DIR_OWNERSHIP_DATA}" = "1" ] || [ "${FIX_DIR_OWNERSHIP_DATA}" = "true" ]; then
  find /data \! \( -uid $(id -u abc) -gid $(id -g abc) \) -print0 | \
    xargs -0 --no-run-if-empty chown -h abc:abc
fi

echo "Flexget v$(flexget -V | sed -n 1p) ready!"
